from __future__ import annotations

import json
from contextlib import AbstractContextManager
from datetime import datetime, timezone
from typing import Callable

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.database import session_scope
from app.domnai_core.contracts import ConversationRequest, ConversationResponse
from app.domnai_core.persistence import ConversationRecord

SessionScopeFactory = Callable[[], AbstractContextManager[Session]]


class PostgresSchemaManager:
    """Cria apenas as tabelas isoladas do novo núcleo, sem tocar no legado."""

    def __init__(self, session_factory: SessionScopeFactory = session_scope) -> None:
        self._session_factory = session_factory

    def ensure_schema(self) -> None:
        with self._session_factory() as session:
            session.execute(text("""
                CREATE TABLE IF NOT EXISTS domnai_core_memory (
                    conversation_id VARCHAR(255) PRIMARY KEY,
                    memory_json TEXT NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
            """))
            session.execute(text("""
                CREATE TABLE IF NOT EXISTS domnai_core_conversation_records (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id VARCHAR(255) NOT NULL DEFAULT '',
                    request_json TEXT NOT NULL,
                    response_json TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
            """))
            session.execute(text("""
                CREATE INDEX IF NOT EXISTS ix_domnai_core_records_conversation
                ON domnai_core_conversation_records (conversation_id, created_at)
            """))


class PostgresMemoryStore:
    def __init__(
        self,
        session_factory: SessionScopeFactory = session_scope,
        *,
        ensure_schema: bool = False,
    ) -> None:
        self._session_factory = session_factory
        if ensure_schema:
            PostgresSchemaManager(session_factory).ensure_schema()

    def load(self, conversation_id: str) -> dict:
        normalized = conversation_id.strip()
        if not normalized:
            return {}
        with self._session_factory() as session:
            row = session.execute(
                text("SELECT memory_json FROM domnai_core_memory WHERE conversation_id = :id"),
                {"id": normalized},
            ).mappings().first()
        if row is None:
            return {}
        value = json.loads(row["memory_json"])
        if not isinstance(value, dict):
            raise ValueError("A memória persistida deve ser um objeto JSON.")
        return value

    def save(self, conversation_id: str, memory: dict) -> None:
        normalized = conversation_id.strip()
        if not normalized:
            raise ValueError("conversation_id não pode ser vazio ao persistir memória.")
        payload = json.dumps(memory, ensure_ascii=False, separators=(",", ":"))
        now = datetime.now(timezone.utc)
        with self._session_factory() as session:
            existing = session.execute(
                text("SELECT conversation_id FROM domnai_core_memory WHERE conversation_id = :id"),
                {"id": normalized},
            ).first()
            if existing is None:
                session.execute(
                    text("""
                        INSERT INTO domnai_core_memory (conversation_id, memory_json, updated_at)
                        VALUES (:id, :memory, :updated_at)
                    """),
                    {"id": normalized, "memory": payload, "updated_at": now},
                )
            else:
                session.execute(
                    text("""
                        UPDATE domnai_core_memory
                        SET memory_json = :memory, updated_at = :updated_at
                        WHERE conversation_id = :id
                    """),
                    {"id": normalized, "memory": payload, "updated_at": now},
                )


class PostgresConversationRepository:
    def __init__(
        self,
        session_factory: SessionScopeFactory = session_scope,
        *,
        ensure_schema: bool = False,
    ) -> None:
        self._session_factory = session_factory
        if ensure_schema:
            PostgresSchemaManager(session_factory).ensure_schema()

    def append(self, record: ConversationRecord) -> None:
        request_payload = _serialize_request(record.request)
        response_payload = _serialize_response(record.response)
        with self._session_factory() as session:
            session.execute(
                text("""
                    INSERT INTO domnai_core_conversation_records
                        (conversation_id, request_json, response_json, created_at)
                    VALUES (:conversation_id, :request_json, :response_json, :created_at)
                """),
                {
                    "conversation_id": record.conversation_id,
                    "request_json": json.dumps(request_payload, ensure_ascii=False, separators=(",", ":")),
                    "response_json": json.dumps(response_payload, ensure_ascii=False, separators=(",", ":")),
                    "created_at": datetime.now(timezone.utc),
                },
            )


def _serialize_request(request: ConversationRequest) -> dict:
    return {
        "message": request.message,
        "history": [{"role": item.role, "content": item.content} for item in request.history],
        "attachments": [
            {"name": item.name, "mime_type": item.mime_type, "size_bytes": len(item.content)}
            for item in request.attachments
        ],
        "operation": request.operation,
        "memory": request.memory,
        "metadata": request.metadata,
    }


def _serialize_response(response: ConversationResponse) -> dict:
    return {
        "text": response.text,
        "provider": response.provider,
        "model": response.model,
        "input_tokens": response.input_tokens,
        "output_tokens": response.output_tokens,
        "cached_input_tokens": response.cached_input_tokens,
        "memory_update": response.memory_update,
        "metadata": response.metadata,
    }
