export const operations = [
  ['validar-ideia-negocio', 'Validar Ideia de Negócio'],
  ['planejar-abertura-empresa', 'Planejar Abertura de Empresa'],
  ['estruturar-processos-negocio', 'Estruturar Processos do Negócio'],
  ['diagnosticar-problemas-empresa', 'Diagnosticar Problemas da Empresa'],
  ['criar-plano-acao-empresarial', 'Criar Plano de Ação Empresarial'],
  ['definir-metas-indicadores', 'Definir Metas e Indicadores'],
  ['pesquisar-mercado-concorrencia', 'Pesquisar Mercado e Concorrência'],
  ['avaliar-viabilidade-financeira-operacional', 'Avaliar Viabilidade Financeira e Operacional'],
  ['analisar-saude-financeira-empresa', 'Analisar Saúde Financeira da Empresa'],
  ['controlar-caixa-conciliacao', 'Controlar Caixa e Conciliação Bancária'],
  ['calcular-preco-venda', 'Calcular Preço de Venda'],
  ['reduzir-custos-operacionais', 'Reduzir Custos Operacionais'],
  ['comparar-cotacoes-empresariais', 'Comparar Cotações Empresariais'],
  ['avaliar-selecionar-fornecedores', 'Avaliar e Selecionar Fornecedores'],
  ['preparar-negociacao-comercial', 'Preparar Negociação Comercial'],
  ['renegociar-dividas-empresariais', 'Renegociar Dívidas Empresariais'],
  ['analisar-contrato-empresarial', 'Analisar Contrato Empresarial'],
  ['mapear-riscos-negocio', 'Mapear Riscos do Negócio'],
  ['organizar-rotinas-administrativas', 'Organizar Rotinas Administrativas'],
  ['melhorar-atendimento-cliente', 'Melhorar Atendimento e Experiência do Cliente'],
  ['comparar-veiculos-compra', 'Comparar Veículos para Compra'],
  ['avaliar-veiculo-usado', 'Avaliar Veículo Usado'],
  ['planejar-manutencao-veiculo', 'Planejar Manutenção Preventiva do Veículo'],
  ['diagnosticar-sintomas-automotivos', 'Diagnosticar Sintomas Automotivos Iniciais'],
  ['avaliar-imovel', 'Avaliar Imóvel para Compra ou Aluguel'],
  ['comparar-financiamento-imobiliario', 'Comparar Opções de Financiamento Imobiliário'],
  ['planejar-reforma-residencial', 'Planejar Reforma Residencial'],
  ['controlar-execucao-obra', 'Controlar Execução da Obra'],
  ['criar-design-interiores', 'Criar Projeto de Design de Interiores'],
  ['organizar-ambientes-pequenos', 'Organizar Ambientes Pequenos'],
  ['cuidar-plantas-domesticas', 'Cuidar de Plantas Domésticas'],
  ['planejar-horta-domestica', 'Planejar Horta Doméstica'],
  ['planejar-instalacao-eletrica', 'Planejar Instalação Elétrica Residencial'],
  ['diagnosticar-problemas-hidraulicos', 'Diagnosticar Problemas Hidráulicos Iniciais'],
  ['reduzir-energia-residencial', 'Reduzir Consumo de Energia Residencial'],
  ['diagnosticar-umidade-mofo', 'Diagnosticar Umidade, Mofo e Infiltração'],
  ['escolher-moveis-eletrodomesticos', 'Escolher Móveis e Eletrodomésticos'],
  ['avaliar-compra-alto-valor', 'Avaliar Compra Pessoal de Alto Valor'],
  ['comparar-seguros-patrimoniais', 'Comparar Seguros Patrimoniais'],
  ['organizar-garantias-bens', 'Organizar Garantias e Manutenção de Bens'],
  ['criar-curriculo-profissional', 'Criar Currículo Profissional'],
  ['preparar-entrevista-emprego', 'Preparar-se para Entrevista de Emprego'],
  ['analisar-caminhos-profissionais', 'Analisar Caminhos Profissionais'],
  ['planejar-transicao-carreira', 'Planejar Transição de Carreira'],
  ['criar-plano-desenvolvimento-profissional', 'Criar Plano de Desenvolvimento Profissional'],
  ['negociar-salario-beneficios', 'Negociar Salário e Benefícios'],
  ['criar-portfolio-profissional', 'Criar Portfólio Profissional'],
  ['desenvolver-marca-pessoal', 'Desenvolver Marca Pessoal'],
  ['melhorar-comunicacao-oratoria', 'Melhorar Comunicação e Oratória'],
  ['preparar-apresentacao-profissional', 'Preparar Apresentação Profissional'],
  ['redigir-emails-profissionais', 'Redigir E-mails e Mensagens Profissionais'],
  ['produzir-relatorios-profissionais', 'Produzir Relatórios Profissionais'],
  ['planejar-estudos-qualificacao', 'Planejar Estudos e Qualificação Profissional'],
  ['organizar-rotina-estudos', 'Organizar Rotina de Estudos'],
  ['planejar-concursos', 'Planejar Preparação para Concursos'],
  ['criar-estrategia-provas', 'Criar Estratégia para Provas e Avaliações'],
  ['criar-plano-idiomas', 'Criar Plano de Aprendizagem de Idiomas'],
  ['praticar-outro-idioma', 'Praticar Comunicação em Outro Idioma'],
  ['desenvolver-lideranca', 'Desenvolver Liderança e Gestão de Equipes'],
  ['resolver-conflitos-trabalho', 'Resolver Conflitos no Trabalho'],
  ['planejar-treino-academia', 'Planejar Treino para Academia'],
  ['planejar-exercicios-casa', 'Planejar Exercícios em Casa'],
  ['preparar-corrida', 'Preparar-se para Corrida'],
  ['desenvolver-condicionamento', 'Desenvolver Condicionamento Físico Geral'],
  ['criar-alongamento-mobilidade', 'Criar Plano de Alongamento e Mobilidade'],
  ['planejar-sono-recuperacao', 'Planejar Sono e Recuperação Física'],
  ['retomar-exercicios', 'Retomar Exercícios após Longa Pausa'],
  ['atividade-fisica-60mais', 'Planejar Atividade Física para Pessoas 60+'],
  ['planejar-yoga-casa', 'Planejar Rotina de Yoga em Casa'],
  ['planejar-pilates-casa', 'Planejar Rotina de Pilates em Casa'],
  ['analisar-alimentacao-fitness', 'Analisar Alimentação e Rotina Fitness'],
  ['planejar-habitos-saudaveis', 'Planejar Hábitos Saudáveis'],
  ['melhorar-ergonomia-postura', 'Melhorar Ergonomia e Postura no Dia a Dia'],
  ['prevenir-dores', 'Organizar Rotina para Prevenção de Dores'],
  ['criar-higiene-bucal', 'Criar Rotina de Higiene Bucal'],
  ['cuidados-aparelho-ortodontico', 'Organizar Cuidados com Aparelho Ortodôntico'],
  ['criar-rotina-pele', 'Criar Rotina de Cuidados com a Pele'],
  ['criar-cronograma-capilar', 'Criar Cronograma Capilar Personalizado'],
  ['organizar-autocuidado', 'Organizar Rotina de Autocuidado'],
  ['manejar-estresse', 'Criar Estratégias para Manejo do Estresse'],
  ['organizar-financas-pessoais', 'Organizar Finanças Pessoais'],
  ['planejar-objetivos-financeiros', 'Planejar Objetivos Financeiros Pessoais'],
  ['planejar-viagem-orcamento', 'Planejar Viagem e Orçamento'],
  ['montar-roteiro-viagem', 'Montar Roteiro Diário de Viagem'],
  ['planejar-evento-festa', 'Planejar Evento ou Festa'],
  ['organizar-convidados', 'Organizar Lista de Convidados e Confirmações'],
  ['organizar-rotina-familiar', 'Organizar Rotina Familiar'],
  ['organizar-rotina-infantil', 'Organizar Rotina Infantil'],
  ['planejar-cardapio-semana', 'Planejar Cardápio da Semana'],
  ['aproveitar-conservar-alimentos', 'Aproveitar e Conservar Alimentos'],
  ['organizar-cuidados-pets', 'Organizar Rotina de Cuidados com Pets'],
  ['adaptar-novo-pet', 'Preparar Adaptação de um Novo Pet'],
  ['planejar-mudanca', 'Planejar Mudança de Casa ou Cidade'],
  ['organizar-documentos-pessoais', 'Organizar Documentos Pessoais'],
  ['melhorar-seguranca-digital', 'Melhorar Segurança Digital Pessoal'],
  ['organizar-arquivos-backups', 'Organizar Arquivos e Backups'],
  ['diagnosticar-computador', 'Diagnosticar Problemas Básicos de Computador'],
  ['configurar-celular-seguranca', 'Configurar e Usar o Celular com Segurança'],
  ['organizar-tarefas-compromissos', 'Organizar Tarefas e Compromissos'],
  ['planejar-compras-mes', 'Planejar Compras do Mês'],
].map(([id, name]) => ({ id, name }));

export const operationGroups = [
  ['Negócios, Contabilidade e Administração', operations.slice(0, 20)],
  ['Compras, Patrimônio, Casa e Manutenção', operations.slice(20, 40)],
  ['Carreira, Educação e Comunicação', operations.slice(40, 60)],
  ['Saúde, Fitness, Beleza e Cuidados', operations.slice(60, 80)],
  ['Vida Pessoal, Família, Tecnologia e Organização', operations.slice(80, 100)],
].map(([name, items]) => ({ name, ids: items.map((item) => item.id) }));

export function operationGroupInitiallyOpen(name, index) {
  try {
    const value = window.localStorage.getItem(`domnai-operation-group:${name}`);
    return value === null ? index === 0 : value === 'open';
  } catch {
    return index === 0;
  }
}

export function persistOperationGroup(name, open) {
  try {
    window.localStorage.setItem(`domnai-operation-group:${name}`, open ? 'open' : 'closed');
  } catch {
    // A navegação continua funcionando quando o armazenamento local está indisponível.
  }
}
